#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-byte-buddy
Version  : 1.8.15
Release  : 6
URL      : https://github.com/raphw/byte-buddy/archive/byte-buddy-1.8.15.tar.gz
Source0  : https://github.com/raphw/byte-buddy/archive/byte-buddy-1.8.15.tar.gz
Source1  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.8.15/byte-buddy-agent-1.8.15.jar
Source2  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.8.15/byte-buddy-agent-1.8.15.pom
Source3  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.8.5/byte-buddy-agent-1.8.5.jar
Source4  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.8.5/byte-buddy-agent-1.8.5.pom
Source5  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.9.7/byte-buddy-agent-1.9.7.jar
Source6  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.9.7/byte-buddy-agent-1.9.7.pom
Source7  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-parent/1.8.15/byte-buddy-parent-1.8.15.pom
Source8  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-parent/1.8.21/byte-buddy-parent-1.8.21.pom
Source9  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-parent/1.8.22/byte-buddy-parent-1.8.22.pom
Source10  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-parent/1.8.5/byte-buddy-parent-1.8.5.pom
Source11  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-parent/1.9.7/byte-buddy-parent-1.9.7.pom
Source12  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.8.15/byte-buddy-1.8.15.jar
Source13  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.8.15/byte-buddy-1.8.15.pom
Source14  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.8.21/byte-buddy-1.8.21.jar
Source15  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.8.21/byte-buddy-1.8.21.pom
Source16  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.8.22/byte-buddy-1.8.22.jar
Source17  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.8.22/byte-buddy-1.8.22.pom
Source18  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.8.5/byte-buddy-1.8.5.jar
Source19  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.8.5/byte-buddy-1.8.5.pom
Source20  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.9.7/byte-buddy-1.9.7.jar
Source21  : https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.9.7/byte-buddy-1.9.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-byte-buddy-data = %{version}-%{release}
Requires: mvn-byte-buddy-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
Byte Buddy
==========
<a href="http://bytebuddy.net">
<img src="https://raw.githubusercontent.com/raphw/byte-buddy/gh-pages/images/logo-bg.png" alt="Byte Buddy logo" height="180px" align="right" />
</a>

%package data
Summary: data components for the mvn-byte-buddy package.
Group: Data

%description data
data components for the mvn-byte-buddy package.


%package license
Summary: license components for the mvn-byte-buddy package.
Group: Default

%description license
license components for the mvn-byte-buddy package.


%prep
%setup -q -n byte-buddy-byte-buddy-1.8.15

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-byte-buddy
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-byte-buddy/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.15
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.15/byte-buddy-agent-1.8.15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.15
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.15/byte-buddy-agent-1.8.15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.5
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.5/byte-buddy-agent-1.8.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.5
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.5/byte-buddy-agent-1.8.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.9.7
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.9.7/byte-buddy-agent-1.9.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.9.7
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.9.7/byte-buddy-agent-1.9.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.15
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.15/byte-buddy-parent-1.8.15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.21
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.21/byte-buddy-parent-1.8.21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.22
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.22/byte-buddy-parent-1.8.22.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.5
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.5/byte-buddy-parent-1.8.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.9.7
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.9.7/byte-buddy-parent-1.9.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.15
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.15/byte-buddy-1.8.15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.15
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.15/byte-buddy-1.8.15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.21
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.21/byte-buddy-1.8.21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.21
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.21/byte-buddy-1.8.21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.22
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.22/byte-buddy-1.8.22.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.22
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.22/byte-buddy-1.8.22.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.5
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.5/byte-buddy-1.8.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.5
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.5/byte-buddy-1.8.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.9.7
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.9.7/byte-buddy-1.9.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.9.7
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.9.7/byte-buddy-1.9.7.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.15/byte-buddy-agent-1.8.15.jar
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.15/byte-buddy-agent-1.8.15.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.5/byte-buddy-agent-1.8.5.jar
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.5/byte-buddy-agent-1.8.5.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.9.7/byte-buddy-agent-1.9.7.jar
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-agent/1.9.7/byte-buddy-agent-1.9.7.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.15/byte-buddy-parent-1.8.15.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.21/byte-buddy-parent-1.8.21.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.22/byte-buddy-parent-1.8.22.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.8.5/byte-buddy-parent-1.8.5.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy-parent/1.9.7/byte-buddy-parent-1.9.7.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.15/byte-buddy-1.8.15.jar
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.15/byte-buddy-1.8.15.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.21/byte-buddy-1.8.21.jar
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.21/byte-buddy-1.8.21.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.22/byte-buddy-1.8.22.jar
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.22/byte-buddy-1.8.22.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.5/byte-buddy-1.8.5.jar
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.8.5/byte-buddy-1.8.5.pom
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.9.7/byte-buddy-1.9.7.jar
/usr/share/java/.m2/repository/net/bytebuddy/byte-buddy/1.9.7/byte-buddy-1.9.7.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-byte-buddy/LICENSE
